# Generated by Django 5.2.4 on 2025-07-07 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('category', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('start_date', models.DateField()),
                ('status', models.CharField(default='Active', max_length=20)),
                ('box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriptions.subscriptionbox')),
            ],
        ),
    ]
